- name: Update apt-get repo and cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist

- name: Install packages
  apt:
    pkg:
      - git
      - vim
      - curl
      - sudo

# - name: Setup config directory
#   become: true
#   file:
#     path: /etc/ansible
#     state: directory
#     owner: "{{ ansible_user }}"