- name: Overwrite bashrc
  ansible.builtin.copy:
    src: ../../.bashrc
    dest: /home/{{ new_user }}/.bashrc
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0644'

- name: Copy aliases
  ansible.builtin.copy:
    src: ../../.bash_aliases
    dest: /home/{{ new_user }}/.bash_aliases
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0644'
