- name: Create vim home dir
  ansible.builtin.file:
    path: /home/{{ new_user }}/.vim
    state: directory
    mode: '0755'

- name: Copy Vim config
  ansible.builtin.copy:
    src: ../../.vimrc
    dest: /home/{{ new_user }}/.vim/vimrc
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0644'